# Generated by Django 3.2.4 on 2021-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('text', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('date_for_user', models.CharField(max_length=30, null=True)),
                ('file_path', models.CharField(max_length=100, null=True)),
                ('body_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('text', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('date_for_user', models.CharField(max_length=30, null=True)),
                ('job_id', models.CharField(max_length=50, null=True)),
                ('file_path', models.CharField(max_length=100, null=True)),
                ('body_type', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=40)),
                ('note_or_reminder_for_edit', models.IntegerField(null=True)),
                ('celery_task_id', models.CharField(max_length=100)),
                ('from_date_for_note', models.DateTimeField(null=True)),
                ('start_reminder_to_show', models.IntegerField(default=0)),
            ],
        ),
    ]
