# Generated by Django 3.2.4 on 2021-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
