# Generated by Django 3.2.4 on 2021-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0002_user_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delay_time',
            field=models.IntegerField(default=10),
        ),
    ]
