# Generated by Django 3.2.4 on 2021-08-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0003_user_delay_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
    ]
