# Generated by Django 3.2.4 on 2021-08-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0004_remove_note_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
