# Generated by Django 3.2.4 on 2021-08-18 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0005_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='from_date_for_note',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 2, 20, 1, 636708), null=True),
        ),
    ]
