# Generated by Django 3.2.4 on 2021-08-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0007_alter_user_from_date_for_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='from_date_for_note',
            field=models.DateTimeField(null=True),
        ),
    ]
