# Generated by Django 3.2.4 on 2021-08-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0008_alter_user_from_date_for_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesFromBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('message_id', models.CharField(max_length=50)),
            ],
        ),
    ]
