# Generated by Django 3.2.4 on 2021-08-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0010_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
