# Generated by Django 3.2.4 on 2021-08-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0011_alter_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='from_date_for_note',
        ),
        migrations.AddField(
            model_name='user',
            name='start_note_to_show',
            field=models.IntegerField(default=0),
        ),
    ]
