# Generated by Django 3.2.4 on 2021-08-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0012_auto_20210820_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesfrombot',
            name='last_default_message',
            field=models.BooleanField(default=False),
        ),
    ]
