# Generated by Django 3.2.4 on 2021-08-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0013_messagesfrombot_last_default_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesfrombot',
            name='last_default_message',
        ),
    ]
