# Generated by Django 3.2.4 on 2021-08-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0014_remove_messagesfrombot_last_default_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_message_cleaning',
            field=models.BooleanField(default=False),
        ),
    ]
