# Generated by Django 3.2.4 on 2021-08-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain_bot_control', '0015_user_enable_message_cleaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celery_task_id',
            field=models.CharField(default='void', max_length=100),
        ),
    ]
